### ISSUE TITLE
Installing on Intel Mac 10.15 w/ Anaconda Python 3.8

### ISSUE THREAD

**Issue by adrn** [GalacticDynamics-Oxford/Agama#14]
Hey Eugene,

This is not a bug report, but wanted to document a hiccup I ran into when building on a new laptop. Using the solutions from #3 got agama and the python wrapper to build, but when I imported from Python I would get:
```
>>> import agama
Fatal Python error: _PyInterpreterState_Get(): no current thread state
Python runtime state: unknown

[1]    83458 abort      python
```

After a bunch of googling, I found some [relevant discussion here](https://stackoverflow.com/questions/48123074/fatal-error-in-extension-pythreadstate-get-no-current-thread). Ultimately, the solution was to add (as suggested in that post)
```
LINK_FLAGS    += -undefined dynamic_lookup
```

🤷

**Comment by eugvas** [comment]
hi Adrian,
thanks for reporting. Are you using the setup.py script or manually creating Makefile.local?
because I think the setup script has a provision for this situation (it's even called "the last resort solution"!)

**Comment by adrn** [comment]
Ah, I see! Yes I was using the Makefile.

**Comment by eugvas** [comment]
is this still relevant? I've updated the installation script a few times in the last couple of years, hopefully it should be resolved now (I noticed that it actually uses the "last resort solution" more often that I expected, but at least it is there).

**Comment by adrn** [comment]
Probably fine to close this, yes!
