### ISSUE TITLE
Feature request: enclosed mass in Python interface

### ISSUE THREAD

**Issue by syrte** [GalacticDynamics-Oxford/Agama#18]
Hi Eugene,
In the C++ part of the documentation, you mentioned  "Methods of the BaseDensity class include **enclosedMass** (compute the mass enclosed within a given spherical radius) and **totalMass**". 
However, it seems only the **totalMass**  being exposed to the Python density/potential object. I am wondering if it would be useful to add enclosedMass to the python interface as well.
(I ask here just in case it is simple to implement, please decide by your own priority of course! :)

In case it may be useful to someone facing the same task as mine, here are two workarounds,
1. The function `totalMass` accepts a single radius as input, unfortunately, it does not support arrays.
2. For a spherical system, one can use `pot.force` to get GM(<r)/r^2 and hence M(<r).

**Comment by eugvas** [comment]
hi Zhaozhou,
indeed, the method totalMass() of a Python Density/Potential class returns the mass enclosed within a given radius (if called with a single argument), i.e. performs the same task as the enclosedMass() method of a C++ BaseDensity class. (somehow I decided to reuse the existing name, previously totalMass() could only be called without arguments and indeed returned the total mass). Is this not what you're looking for? Or you want a version with a vectorized (and internally parallelized) argument - I can add this option rather easily, if needed.

**Comment by syrte** [comment]
Thanks for your explanation! And sorry for my late reply...
Yes, I am looking for a vectorized version of totalMass. It would be great if you can add it easily.
For now, I am using pot.force as a vectorized workaround.

**Comment by eugvas** [comment]
done! I reverted totalMass() to compute just the total mass and accept no arguments, and created a new method enclosedMass(r) that accepts one or more values of radius and parallelizes the computation with OpenMP if the input is an array.

**Comment by syrte** [comment]
Great news! Thanks, Eugene!
