### ISSUE TITLE
Number of sampling points of an orbit not equal to the requested value.

### ISSUE THREAD

**Issue by VictorForouhar** [GalacticDynamics-Oxford/Agama#22]
# Code
Tested using Python 3.6.5, Agama 1.0 and Numpy 1.19.5.

# Issue
I want to integrate the orbit of an object (taken from an N-body simulation) and sample its position along the orbit N times. However, I find that depending on the specified integration time range, you might obtain N-1 sampling points. 

I suspect this is related to rounding, since whether I get the expected behaviour or not is dependent on whether I use times as directly measured from the simulation, copying the values printed in the console when I call print(simulation_times) or if I set the starting integration time equal to 0. A screenshot showing this behaviour is shown below for the example of N = 2.
![image](https://user-images.githubusercontent.com/60343271/159344744-e98e4947-4952-4170-866d-d277436243a3.png)

# Example code   
I have attached the script used to generate the outputs shown above, as well as the potential, object ICs and time range values. 
[example.tar.gz](https://github.com/GalacticDynamics-Oxford/Agama/files/8318521/example.tar.gz)

**Comment by eugvas** [comment]
thanks for reporting in a beautifully clean way! This is a simple roundoff problem that is easy to control, I've seen it before and already implemented a solution, but it still contained a bug! now it should be fixed in the latest commit.

**Comment by VictorForouhar** [comment]
Thank you for letting me know! Tested using the above script and I now get the correct number of sampling points in all three cases :)
