### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by brugalada** [GalacticDynamics-Oxford/Agama#26]
Hi!

I have been using the ActionMapper method heavily and I noticed that, whenever I use it, the memory pressure only increases (and very fast). Even when it is finished, or even if I delete the ActionMapper object and create it again when I move from one set of actions to the next set in the 3D grid I am using, the allocated memory does not go down.

I am wondering if I am doing something wrong or not but a simple call like
```
%%timeit -n 1000
am = agama.ActionMapper(pot, np.array([240.00000066666666, 1e-01, 360.0]))
```
made python consume 1Gb of RAM in seconds, which I cannot get back until I restart my Jupyter kernel. Could it be this the issue? That I work with Jupyter notebooks?

Thank you in advance!

**Comment by eugvas** [comment]
yes, there was a memory leak; fixed in the latest commit.
