### ISSUE TITLE
Use of new models

### ISSUE THREAD

**Issue by Kyrie-Irving-Sgc** [GalacticDynamics-Oxford/Agama#27]
Hi！

I noticed that you published about the new distribution functions exponential model some time ago(James Binney and Eugene Vasiliev 2022), but when I quoted it，it return "Error in creating distribution function: Unknown type of distribution function". I have tried to reinstall Agama, but there are still error. So, how should I use the new model？

Thank you very much!

**Comment by eugvas** [comment]
hehe, I didn't expect that people are eager to start using these models immediately!
Indeed, the new disk and halo DFs are not yet included into the list of built-in models, so are not available in the Python interface. I still need to decide on the details (whether to add them independently, or replace existing DF classes, or generalize them to use both new and old sets of parameters).
For now, there is a C++ program `tests/example_self_consistent_model_mw.cpp`, which implements these DFs "in the user space" (not within the main Agama library) and creates the MW model with the fiducial parameters - it produces the potential in the form compatible with the rest of the library, computes DF moments and velocity distributions at several points in space, etc., so can serve as a foundation for further modifications (but you'll need to write C++ code). Eventually I plan to include the DFs to the core library and add an equivalent Python script for creating the MW model.

**Comment by Kyrie-Irving-Sgc** [comment]
Thanks for your reply! Looking forward to the updating of the code!

**Comment by eugvas** [comment]
hopefully in a month or so, I'll keep the issue open until then.

**Comment by eugvas** [comment]
the models from Binney&Vasiliev were constructed using a customized version of code that has diverged enough from the main branch to merit its own separate repository (not to say that it is better or worse, just different enough..): https://github.com/GalacticDynamics-Oxford/AgamaChemo

**Comment by eugvas** [comment]
Somehow it took me over two years to come up with a Python implementation of the "new" DFs introduced in Binney&Vasiliev 2023, now available as `example_self_consistent_model.py`. They are still not included in the main branch of code, but are available as user-defined Python functions fed into the self-consistent modelling machinery. Of course, this is slower than the pure-C++ implementation in `example_self_consistent_model.cpp`, but to my surprise, the difference is not enormous (~1.5-2x on a 4-8 core system).
To clarify, this model is purely dynamical and fitted to the Gaia DR2 data. The second paper (Binney&Vasiliev 2024) somewhat tweaked the DF parameters and fitted _chemodynamical_ models to the combination of Gaia DR3 and APOGEE. These updated models are not included in the main Agama repository, and probably will never be; instead, they are available in a different version of code linked above.
