### ISSUE TITLE
explicitly including G  in the calculation of Toomre Q in the example?

### ISSUE THREAD

**Issue by YiruiZheng** [GalacticDynamics-Oxford/Agama#28]
In the example code _example_self_consistent_model3.py_, the author calculates the Toomre Q values with:
`
ToomreQ = sigma[:,0]**0.5 * kappa / 3.36 / Sigma
`
This formula works fine with the default Agama unit system, in which G=1. 
However, if one revises this code for their models and changes the unit system, the code will then give wrong Toomre Q values.
I would suggest **explicitly including G** in the formula and updating it to be
`
ToomreQ = sigma[:,0]**0.5 * kappa / 3.36 / Sigma / agama.G
`
It is a tiny issue but solving it may provide some tiny benefits. 

Thanks!

**Comment by eugvas** [comment]
thanks for the suggestion; implemented in the latest commit.
