### ISSUE TITLE
Installing on Mac with Python 3.7

### ISSUE THREAD

**Issue by adrn** [GalacticDynamics-Oxford/Agama#3]
Hey Eugene --

I'm trying to install Agama on a new machine running Mac 10.14.6 with an Anaconda installed Python 3.7. 

I would rather not install a new C compiler and have to re-install Python and many other things, so I'm trying to roll with Clang and no OpenMP. I have gsl installed, but also into the Anaconda path. I created and edited a Makefile.local to add:
```
COMPILE_FLAGS += -I/Users/apricewhelan/anaconda/include/
LINK_FLAGS    += -L/Users/apricewhelan/anaconda/lib/ -lgsl -lgslcblas
```
and removed `-fopenmp`. I have gfortran installed, but also ran into issues compiling the Fortran code, so I commented out the Fortran compile lines in `Makefile` - they look like they only run a test file, so it didn't seem crucial, but maybe this is a problem?

In any case, running `make` does succeed, and it produces the `agama.so` shared library. However, when I try to import with Python, I get:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dynamic module does not define module export function (PyInit_agama)
```

Any ideas?

**Comment by eugvas** [comment]
Hi Adrian,
so you're not using the "recommended way" (setup.py)? any specific reason? it should create Makefile.local with sensible values, and you can always edit it later (e.g., if you want to use system-installed GSL instead of the one that the installer downloads), and rerun make.
The error may be due to either the file agama.so compiled against a different Python major version (in Py2 the module export function would be called "initagama" and not "PyInit_agama"), or even more simply, because the Makefile.local did not contain -DHAVE_PYTHON among COMPILE_FLAGS (yes, it can be compiled as a pure C++ library, without any Python support!)
By the way, recent versions of clang (starting from MacOS 10.13 I believe) actually can use OpenMP parallelization, but it requires some fiddling with makefile options - again, if available, they would be selected by setup.py
Finally, a single fortran example can be ignored entirely - if it doesn't compile, no one will complain, no need to remove it from Makefile.

**Comment by adrn** [comment]
> so you're not using the "recommended way" (setup.py)? any specific reason? it should create Makefile.local with sensible values, and you can always edit it later (e.g., if you want to use system-installed GSL instead of the one that the installer downloads), and rerun make.

My GSL is installed in my Anaconda directory structure, and I couldn't convince the `setup.py` script to find it. I tried setting C_INCLUDE_PATH and CPLUS_INCLUDE_PATH but it couldn't find the gsl header files.

> The error may be due to either the file agama.so compiled against a different Python major version (in Py2 the module export function would be called "initagama" and not "PyInit_agama"), or even more simply, because the Makefile.local did not contain -DHAVE_PYTHON among COMPILE_FLAGS (yes, it can be compiled as a pure C++ library, without any Python support!)

Ah, interesting. I'll look in to to see if it accidentally found the system Python (2.7).

> By the way, recent versions of clang (starting from MacOS 10.13 I believe) actually can use OpenMP parallelization, but it requires some fiddling with makefile options - again, if available, they would be selected by setup.py

Interesting! I didn't know that.

> Finally, a single fortran example can be ignored entirely - if it doesn't compile, no one will complain, no need to remove it from Makefile.

It was failing on that, so I had to remove it?

~~~

But, now all of this might be irrelevant for me anyways: I installed Agama on our local cluster and everything went fine :)

**Comment by eugvas** [comment]
> My GSL is installed in my Anaconda directory structure, and I couldn't convince the `setup.py` script to find it. I tried setting C_INCLUDE_PATH and CPLUS_INCLUDE_PATH but it couldn't find the gsl header files.

I think you might have some luck with setting CFLAGS="-I/path/to/gsl/include" and LDFLAGS="-L/path/to/gsl/lib". But it wouldn't hurt if the installer downloads and compiles its own preferred copy of GSL, which will be statically linked into agama.so, and will not interfere with the system-wide one.

> Ah, interesting. I'll look in to to see if it accidentally found the system Python (2.7).

I think that if you run python setup.py install, and "python" here points to your anaconda version 3.x, not to the system one (2.x), then it will link correctly against the version 3, if needed, by adding explicit paths to the makefile. But if you just create Makefile.local yourself (without setup.py), it might well pick up the wrong one.

> >  By the way, recent versions of clang (starting from MacOS 10.13 I believe) actually can use OpenMP parallelization
> Interesting! I didn't know that.

yes, basically the compiler supports the OpenMP directives, but is not supplied with the runtime library. The trick is to use "-Xpreprocessor -fopenmp" during compilation, and add "-lomp" or "-lgomp" during linking - then it will pick up the gomp shared library installed by something else.

> > Finally, a single fortran example can be ignored entirely - if it doesn't compile, no one will complain, no need to remove it from Makefile. 
> It was failing on that, so I had to remove it?

no, if it fails during make, the error is ignored (although still displayed on the screen).

**Comment by adrn** [comment]
Oops, looks like I forgot to respond, but I did get this all to work eventually!
