### ISSUE TITLE
document of Einasto profile

### ISSUE THREAD

**Issue by syrte** [GalacticDynamics-Oxford/Agama#35]
Hi Eugene, 
I am using the Einasto profile and want to make sure I understand the document correctly. The "eta" mentioned here
<img width="1003" alt="image" src="https://user-images.githubusercontent.com/7038335/235209216-a88f03cd-4269-48af-aa20-84930636c9e7.png">
is the same "eta" in the following?
<img width="999" alt="image" src="https://user-images.githubusercontent.com/7038335/235209833-0c9c41d8-b807-4140-9449-390d66dfb884.png">
Or is it a typo of "xi=1/n"?

Thanks!

**Comment by eugvas** [comment]
you're right, this is a typo in the docs - should be $\xi = 1/n$. Setting gamma=beta=0 makes eta irrelevant, there is no power-law component in the density profile, only the exponential cutoff. Adding a power-law would be suitable for something like Prugniel-Simien profile, which itself was designed as an analytic approximation for the deprojected Sersic profile, but the latter is available in Agama directly (via a numerical deprojection).
I will correct the docs in the next commit.

**Comment by syrte** [comment]
Thanks for the clarification!
