### ISSUE TITLE
Versioned tag or release plan

### ISSUE THREAD

**Issue by Hellseher** [GalacticDynamics-Oxford/Agama#36]
Hi!

I am preparing your project for inclusion in [Guix's](https://guix.gnu.org/) Astronomical packages collection and have noticed that the code has never been released and there are no versioned tags in Git. Having a release version would help package maintainers to update it downstream.

I would use the latest commit of  the current master branch.

Thanks,
Oleg.

**Comment by eugvas** [comment]
that's right, there are formal releases or versions, other than git commits, so feel free to use the latest one.

**Comment by Hellseher** [comment]
Hi @eugvas,

Thank you for your replay, may you share the link on formal release and version
please? I can't find it in tags, GitHub's release or README.

Regards,
Oleg

**Comment by eugvas** [comment]
sorry, I missed a crucial word in my comment: there are *no* formal releases or versions! 
the pip install script simply pulls the latest commit from github, and that's it.
