### ISSUE TITLE
About the tolerance of the Torus Mapper fitting

### ISSUE THREAD

**Issue by brugalada** [GalacticDynamics-Oxford/Agama#40]
This is probably an out-of-place question but... is there a way to set the tolerance of the fitting process happening in the Torus Mapper routine?

Well, in reality, what I want to know is the default tolerance in case the referee asks me jeje I did not find it in the documentation and digging into the C code looks time consuming, so I thought I should ask first before starting in case it was written somewhere.

Thanks in advance!

**Comment by eugvas** [comment]
yes, it is the optional argument "tol" in the constructor of `agama.ActionMapper` (if you're talking about the Python interface), or the equivalent argument in `createActionMapper` routine (C++).

**Comment by brugalada** [comment]
Thank you as always ^^

Let me just write here, for completeness, that the default value of the tolerance I found is 0.003 of |dJ|/|J|. Taken from Torus.h (AutoFit) and from actions_torus.h (ActionMapperTorus).
