### ISSUE TITLE
Windows Installation not working

### ISSUE THREAD

**Issue by titanbin** [GalacticDynamics-Oxford/Agama#41]
I am trying to install Agama on my Windows 10x64 machine, however the `setup.py` script seems to have issues, making it crash on the GSL installation step :

- the variable `commitname` is undefined (used on `line 542`), which I am guessing should be set to the same value as the variable `archivename` as that will be the way the folder in the git archive will be named.
- the hash `de1c175ee239ea0f243bf72016bad2e53338e830` does not resolve to a valid commit on the `https://github.com/BrianGladman/gsl/` repository, making the retrieval of the gsl archive fail.
- Even after fixing these issues (by using the latest commit of the gsl repo), line `558`, `os.chdir(dirname+'\\build.vc')` crashes because no such directory exists in the uncompressed archive of the gsl repository, which I am not sure how to fix. My only guess is that this directory was part of an older commit and was later removed so that it is not present in the up to date repo of gsl ?

**Comment by eugvas** [comment]
Indeed, the GSL-Windows distribution on Github seems to lack the files necessary for building it. I changed the setup script to download an archived version of GSL with these files included, it seems to work on my system, please check the latest commit.

**Comment by titanbin** [comment]
Thank you, the new setup works perfectly on my machine !
