### ISSUE TITLE
How to create a self-consistent model with custom mass distribution

### ISSUE THREAD

**Issue by savchenkoyana** [GalacticDynamics-Oxford/Agama#48]
Hello Eugene Vasiliev! Thank you for AGAMA framework, it is very useful!

I want to use AGAMA for my task but not sure how to properly do this. Could you please help me out? 🙏 

My goal is to create a self-consistent model given both custom density profile and custom mass distribution. I noticed that when I create a model for a given density profile and sample N points, all masses are equal.

What should I do to get masses that are distributed according to my `f_m(m)`? Should it (a) be a slight modification when I call `sample` method or (b) should I also add modifications to the self-consistent modelling code?

If you give me any additional hints, that would help a lot

Sincerely,
Yana

**Comment by eugvas** [comment]
I think this question is entirely about sampling, so the self-consistent modelling aspect is not affected.
Indeed, the sampling routine produces equal-mass samples by construction. If your goal is to convert them into samples from an IMF that is independent of location, then I would suggest the following approach:
- first create an equal-mass sample;
- then randomly reassign particle masses in such a way that their total mass and total number remain unchanged, but the mass is drawn from a prescribed mass distribution. On average this will preserve the dynamical equilibrium of the model.

**Comment by savchenkoyana** [comment]
Thank you very much! You are a lifesaver! 👍 

> I think this question is entirely about sampling, so the self-consistent modelling aspect is not affected. Indeed, the sampling routine produces equal-mass samples by construction. If your goal is to convert them into samples from an IMF that is independent of location, then I would suggest the following approach:
> 
>     * first create an equal-mass sample;
> 
>     * then randomly reassign particle masses in such a way that their total mass and total number remain unchanged, but the mass is drawn from a prescribed mass distribution. On average this will preserve the dynamical equilibrium of the model.
