### ISSUE TITLE
Support for python 3.12 - numpy distutils

### ISSUE THREAD

**Issue by nbrucy** [GalacticDynamics-Oxford/Agama#51]
Dear mainteners,

Agama's installer relies on `numpy.distutils`, which is deprecated since python 3.12 (see [https://numpy.org/doc/stable/reference/distutils_status_migration.html#distutils-status-migration](https://numpy.org/doc/stable/reference/distutils_status_migration.html#distutils-status-migration)).

Is there any plan to switch to an alternative to support newer version of Python?

Cheers,
Noé.

**Comment by eugvas** [comment]
it works fine with Python 3.12 and 3.13, but you have to invoke the installer as `pip install .` (if installing from the local directory) or `pip install agama` (this downloads the latest version from the github repository first, and then proceeds as before).

**Comment by nbrucy** [comment]
Thanks for your answer. Indeed (my bad), distutils was only used to find the numpy header (in  `Makefile.local.template`), and not for the rest. 

Maybe these lines need to be updated.
```
# The full path to numpy headers is easier to find: just type
# > python -c 'import numpy.distutils; print(numpy.distutils.misc_util.get_numpy_include_dirs())'
```

**Comment by eugvas** [comment]
oh yes, thanks for spotting! this recommendation is indeed very outdated, and the same information can be obtained from `numpy.get_include()` – I will update the text in Makefile.local.template in the next commit. I don't expect it to be used in practice, anyway – the `setup.py` script currently handles a lot more complicated situations than those described in that template file.
PS – I don't understand the push of Python maintainers to "deprecate" the setup.py script, and in fact `pip install .` calls it under the hood anyway. There are many steps during the installation that cannot be described in a `pyproject.toml` file, which is a supposedly modern replacement for `setup.py`...

**Comment by nbrucy** [comment]
Manual editing of the `Makefile.local` is still useful, especially in on clusters when finfing the installation path of GSL is not always straightforward.

**Comment by eugvas** [comment]
I'm usually not concerned about finding the system-wide GSL library installation, since the setup script downloads and compiles its own copy if needed (and I'd say this is a preferred solution). More important is the determination of linking flags for the Python extension module, which is not trivial and is the main challenge that is being addressed by the setup script.
If it does not work automatically on some systems, do let me know what goes wrong (attach the full output from terminal after running `pip install .`).
