### ISSUE TITLE
Accessing a Potential's multipole coefficients in Python

### ISSUE THREAD

**Issue by nstarman** [GalacticDynamics-Oxford/Agama#9]
@eugvas Is it possible to access a multipole potential's coefficients in python (or even to save the coefficients to a file)?

**Comment by eugvas** [comment]
the coefficients are indeed written to text files by the Potential.export() method, though the detailed specification of this file is not given in the docs. But it does have a rather simple structure: after a few header lines, there comes an array of potential coefficients, followed by radial derivative coefficients:  Phi_{lm}(r), dPhi_{lm}/dr. Each line contains the radius and then the values of each potential harmonic at this radius, in the following order:   l=0;   l=1,m=-1;  l=1,m=0;  l=1,m=1;  l=2,m=-2;  l=2,m=-1;  etc., where negative m correspond to sine and positive - to cosine terms in the expansion - in total, (lmax+1)^2 terms. The normalization convention is described in the section A.4.1 of reference.pdf
Although there is no way to access these coefs from Python, you may save them to a file and read it off as a numpy array if needed.

**Comment by nstarman** [comment]
Thanks @eugvas !
